backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "inventory"
    label: "Shop Inventory"
    folder: "content/inventory"
    create: true # This allows her to add new clothes
    delete: true # This allows her to REMOVE clothes
    slug: "{{slug}}"
    fields:
      - { label: "Product Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["suit", "collection", "solar", "books"] }
      - { label: "Product Image", name: "image", widget: "image" }

  - name: "settings"
    label: "Site Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "contact_info"
        label: "Contact & Socials"
        file: "content/settings/contact.json"
        fields:
          - { label: "WhatsApp Number", name: "whatsapp", widget: "string" }
          - { label: "Business Location", name: "address", widget: "text" }
          - { label: "Shop Intro Text", name: "intro", widget: "text" }
